### PR TITLE
chore: unify model and directory naming

### PR DESCRIPTION
**Pull request by alex-lee-tessella**

### CODE REVIEW

**Comment by akademy** [comment]
I was trying not to draw too much attention to the Fibinacci part of this model as I thought that might discourage people from exploring it. "Simple model" was nice and friendly ;)

**Comment by akademy** [comment]
Are there references in the model upload documentation that we will also need to change?

**Comment by alex-lee-tessella** [comment]
> I was trying not to draw too much attention to the Fibinacci part of this model as I thought that might discourage people from exploring it. "Simple model" was nice and friendly ;)

That is a good point! Hopefully now have the tiny example we can use that as the really simple example and the Fibonacci as a slightly more fleshed out one!

**Comment by alex-lee-tessella** [comment]
> Are there references in the model upload documentation that we will also need to change?

Yes there are, that is what I'm working on now

**Review by akademy — APPROVED** [review]
Looks fine.

**Review by akademy — APPROVED** [review]

**Review by tg137 — APPROVED** [review]
LGTM!

**Pull request merged**
